version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: unicorn_user
      POSTGRES_PASSWORD: magical_password
      POSTGRES_DB: rainbow_database
    ports:
    - '5432:5432'
